<a href="https://colab.research.google.com/github/darsan-0/Python_lib_for_ML/blob/main/Pandas_DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eve","Alice"],
    "age": [30, 24, 45, np.nan, 29,30],
    "department": ["HR", "IT", "Finance", "IT", "HR","HR"],
    "salary": [60000, np.nan, 90000, 70000, 62000,60000]
}
df = pd.DataFrame(data)
df

      name   age department   salary
0    Alice  30.0         HR  60000.0
1      Bob  24.0         IT      NaN
2  Charlie  45.0    Finance  90000.0
3    David   NaN         IT  70000.0
4      Eve  29.0         HR  62000.0
5    Alice  30.0         HR  60000.0

In [ ]:
# sawa Starting few rows --->head(Value),Value not manadory defalut - 5.
df.head(3)

      name   age department   salary
0    Alice  30.0         HR  60000.0
1      Bob  24.0         IT      NaN
2  Charlie  45.0    Finance  90000.0

In [ ]:
# sawa Ending few rows --->tail(Value),Value not manadory defalut - 5.
df.tail(2)

    name   age department   salary
4    Eve  29.0         HR  62000.0
5  Alice  30.0         HR  60000.0

In [ ]:
# loc and iloc
df.iloc[1:3] #row,column

      name   age department   salary
1      Bob  24.0         IT      NaN
2  Charlie  45.0    Finance  90000.0

In [ ]:
df.loc[1:3,["name","department","age"]]

      name department   age
1      Bob         IT  24.0
2  Charlie    Finance  45.0
3    David         IT   NaN

In [ ]:
#Accesing required column.
df[['age',"salary"]]

    age   salary
0  30.0  60000.0
1  24.0      NaN
2  45.0  90000.0
3   NaN  70000.0
4  29.0  62000.0
5  30.0  60000.0

In [ ]:
df.drop("age",axis=1,inplace=False)# if inplace is True the age column was compltely deleteed.
# axis=1 specifes you wants to delete complte column...if axis=0 then you can choose requied row to drop it...

      name department   salary
0    Alice         HR  60000.0
1      Bob         IT      NaN
2  Charlie    Finance  90000.0
3    David         IT  70000.0
4      Eve         HR  62000.0
5    Alice         HR  60000.0

In [ ]:
df.drop(2, axis=0, inplace=False)

    Name   Age Dept   salary  promoted salary
0  Alice  30.0   HR  65000.0         650000.0
1    Bob  24.0   IT      NaN              NaN
3  David  31.6   IT  75000.0          75000.0
4    Eve  29.0   HR  67000.0          67000.0

In [ ]:
df

      name   age department   salary
0    Alice  30.0         HR  60000.0
1      Bob  24.0         IT      NaN
2  Charlie  45.0    Finance  90000.0
3    David   NaN         IT  70000.0
4      Eve  29.0         HR  62000.0
5    Alice  30.0         HR  60000.0

In [ ]:
df.shape

(6, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        6 non-null      object
 1   age         5 non-null      float64
 2   department  6 non-null      object
 3   salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [ ]:
df.describe()

             age        salary
count   5.000000      5.000000
mean   31.600000  68400.000000
std     7.893035  12759.310326
min    24.000000  60000.000000
25%    29.000000  60000.000000
50%    30.000000  62000.000000
75%    30.000000  70000.000000
max    45.000000  90000.000000

In [ ]:
#Broadcasting
df['salary']=df['salary']+5000

In [ ]:
df

      name   age department   salary
0    Alice  30.0         HR  65000.0
1      Bob  24.0         IT      NaN
2  Charlie  45.0    Finance  95000.0
3    David   NaN         IT  75000.0
4      Eve  29.0         HR  67000.0
5    Alice  30.0         HR  65000.0

In [ ]:
#Renamimg columns:
df.rename(columns={"department":"Dept","age":"Age","name":"Name"},inplace=True)

In [ ]:
df

      Name   Age     Dept   salary
0    Alice  30.0       HR  65000.0
1      Bob  24.0       IT      NaN
2  Charlie  45.0  Finance  95000.0
3    David   NaN       IT  75000.0
4      Eve  29.0       HR  67000.0
5    Alice  30.0       HR  65000.0

In [ ]:
#To find out unique value in the specified column..
df['Name'].unique()

array(['Alice', 'Bob', 'Charlie', 'David', 'Eve'], dtype=object)

In [ ]:
df["Dept"].value_counts()

Dept
HR         2
IT         2
Finance    1
Name: count, dtype: int64

In [ ]:
#inserting new date into a dataframe
df['promoted salary'] = df['salary'] * 10
df

      Name   Age     Dept   salary  promoted salary
0    Alice  30.0       HR  65000.0         650000.0
1      Bob  24.0       IT      NaN              NaN
2  Charlie  45.0  Finance  95000.0         950000.0
3    David   NaN       IT  75000.0         750000.0
4      Eve  29.0       HR  67000.0         670000.0
5    Alice  30.0       HR  65000.0         650000.0

In [ ]:
#Data cleaning

#->1.Checking null values in the dataframe on all columns.
df.isnull().sum()

Name               0
Age                1
Dept               0
salary             1
promoted salary    1
dtype: int64

In [ ]:
df['Age'].fillna(df['Age'].mean(),inplace=True)

/tmp/ipython-input-694922604.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)

In [ ]:
df

      Name   Age     Dept   salary  promoted salary
0    Alice  30.0       HR  65000.0         650000.0
1      Bob  24.0       IT      NaN              NaN
2  Charlie  45.0  Finance  95000.0         950000.0
3    David  31.6       IT  75000.0         750000.0
4      Eve  29.0       HR  67000.0         670000.0
5    Alice  30.0       HR  65000.0         650000.0

In [ ]:
df['Name']=df['Name'].replace('Charlie','Darsan')

In [ ]:
df

     Name   Age     Dept   salary  promoted salary
0   Alice  30.0       HR  65000.0         650000.0
1     Bob  24.0       IT      NaN              NaN
2  Darsan  45.0  Finance  95000.0         950000.0
3   David  31.6       IT  75000.0         750000.0
4     Eve  29.0       HR  67000.0         670000.0
5   Alice  30.0       HR  65000.0         650000.0

In [ ]:
#->2.Delaling with duplicate values...
df_dup = df[df.duplicated]
df_dup

    Name   Age Dept   salary  promoted salary
5  Alice  30.0   HR  65000.0         650000.0

In [ ]:
df = df.drop_duplicates()

In [ ]:
df

     Name   Age     Dept   salary  promoted salary
0   Alice  30.0       HR  65000.0         650000.0
1     Bob  24.0       IT      NaN              NaN
2  Darsan  45.0  Finance  95000.0         950000.0
3   David  31.6       IT  75000.0         750000.0
4     Eve  29.0       HR  67000.0         670000.0

In [ ]:
# invalid values:
# Lambda -> python
df["promoted salary"] = df["promoted salary"].apply(lambda x: x/10 if x > 650000 else x)

/tmp/ipython-input-3120380552.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["promoted salary"] = df["promoted salary"].apply(lambda x: x/10 if x > 650000 else x)

In [ ]:
df

     Name   Age     Dept   salary  promoted salary
0   Alice  30.0       HR  65000.0         650000.0
1     Bob  24.0       IT      NaN              NaN
2  Darsan  45.0  Finance  95000.0          95000.0
3   David  31.6       IT  75000.0          75000.0
4     Eve  29.0       HR  67000.0          67000.0

In [ ]:
#Joins and Merges
department_info ={
    "Dept":["HR","IT","Finance"],
    "Location":["New York","San Francisco", "Chicago"],
    "Manager":["Laura","Steve","Nina"]
}

In [ ]:
df2 = pd.DataFrame(department_info)
df2

      Dept       Location Manager
0       HR       New York   Laura
1       IT  San Francisco   Steve
2  Finance        Chicago    Nina

In [ ]:
#Concat
pd.concat([df,df2],axis=1)

,Name,Age,Dept,salary,promoted salary,Dept,Location,Manager
0,Alice,30.0,HR,65000.0,650000.0,HR,New York,Laura
1,Bob,24.0,IT,NaN,NaN,IT,San Francisco,Steve
2,Darsan,45.0,Finance,95000.0,95000.0,Finance,Chicago,Nina
3,David,31.6,IT,75000.0,75000.0,NaN,NaN,NaN
4,Eve,29.0,HR,67000.0,67000.0,NaN,NaN,NaN

In [ ]:
#Merge
pd.merge(df,df2,on="Dept")

     Name   Age     Dept   salary  promoted salary       Location Manager
0   Alice  30.0       HR  65000.0         650000.0       New York   Laura
1     Bob  24.0       IT      NaN              NaN  San Francisco   Steve
2  Darsan  45.0  Finance  95000.0          95000.0        Chicago    Nina
3   David  31.6       IT  75000.0          75000.0  San Francisco   Steve
4     Eve  29.0       HR  67000.0          67000.0       New York   Laura

Importing File

In [ ]:
data = pd.read_csv("/Exam_Score_Prediction.csv")

In [ ]:
df1 = pd.DataFrame(data)

In [ ]:
df1.head(10)

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,1,17,male,diploma,2.78,92.9,yes,7.4,poor,coaching,low,hard,58.9
1,2,23,other,bca,3.37,64.8,yes,4.6,average,online videos,medium,moderate,54.8
2,3,22,male,b.sc,7.88,76.8,yes,8.5,poor,coaching,high,moderate,90.3
3,4,20,other,diploma,0.67,48.4,yes,5.8,average,online videos,low,moderate,29.7
4,5,20,female,diploma,0.89,71.6,yes,9.8,poor,coaching,low,moderate,43.7
5,6,23,male,b.tech,3.48,65.4,yes,4.2,good,mixed,low,moderate,58.2
6,7,17,female,b.tech,1.35,69.0,yes,7.4,average,online videos,high,hard,53.7
7,8,22,male,b.sc,5.48,51.1,yes,8.2,poor,self-study,low,moderate,47.3
8,9,18,other,bca,2.89,92.0,yes,6.6,poor,self-study,low,easy,44.9
9,10,17,male,bba,6.77,44.8,yes,9.8,average,group study,high,moderate,77.7

In [ ]:
data.head()

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,1,17,male,diploma,2.78,92.9,yes,7.4,poor,coaching,low,hard,58.9
1,2,23,other,bca,3.37,64.8,yes,4.6,average,online videos,medium,moderate,54.8
2,3,22,male,b.sc,7.88,76.8,yes,8.5,poor,coaching,high,moderate,90.3
3,4,20,other,diploma,0.67,48.4,yes,5.8,average,online videos,low,moderate,29.7
4,5,20,female,diploma,0.89,71.6,yes,9.8,poor,coaching,low,moderate,43.7

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        20000 non-null  int64
 1   age               20000 non-null  int64
 2   gender            20000 non-null  object
 3   course            20000 non-null  object
 4   study_hours       20000 non-null  float64
 5   class_attendance  20000 non-null  float64
 6   internet_access   20000 non-null  object
 7   sleep_hours       20000 non-null  float64
 8   sleep_quality     20000 non-null  object
 9   study_method      20000 non-null  object
 10  facility_rating   20000 non-null  object
 11  exam_difficulty   20000 non-null  object
 12  exam_score        20000 non-null  float64
dtypes: float64(4), int64(2), object(7)
memory usage: 2.0+ MB

In [ ]:
df1[["study_hours","sleep_quality"]].head(10)

   study_hours sleep_quality
0         2.78          poor
1         3.37       average
2         7.88          poor
3         0.67       average
4         0.89          poor
5         3.48          good
6         1.35       average
7         5.48          poor
8         2.89          poor
9         6.77       average

In [ ]:
df1.loc(20:30,["study_hours","sleep_quality"])

SyntaxError: invalid syntax (ipython-input-2446455998.py, line 1)

In [ ]:
data.shape

(20000, 13)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        20000 non-null  int64
 1   age               20000 non-null  int64
 2   gender            20000 non-null  object
 3   course            20000 non-null  object
 4   study_hours       20000 non-null  float64
 5   class_attendance  20000 non-null  float64
 6   internet_access   20000 non-null  object
 7   sleep_hours       20000 non-null  float64
 8   sleep_quality     20000 non-null  object
 9   study_method      20000 non-null  object
 10  facility_rating   20000 non-null  object
 11  exam_difficulty   20000 non-null  object
 12  exam_score        20000 non-null  float64
dtypes: float64(4), int64(2), object(7)
memory usage: 2.0+ MB