<a href="https://colab.research.google.com/github/darsan-0/Python_lib_for_ML/blob/main/Pandas_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
s = pd.Series([10,20,30,40,50])
s.name = 'calouries'
s

0    10
1    20
2    30
3    40
4    50
Name: calouries, dtype: int64

In [3]:
s.dtype

dtype('int64')

In [4]:
s.values

array([10, 20, 30, 40, 50])

In [5]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
s[0:1]

0    10
Name: calouries, dtype: int64

In [7]:


s[0:2]

0    10
1    20
Name: calouries, dtype: int64

In [8]:
#iloc --> Location Based Indexing
s.iloc[0]

np.int64(10)

In [9]:
s.iloc[[0,2,4]]

0    10
2    30
4    50
Name: calouries, dtype: int64

In [10]:
ind = ['Appel','Banana','orange','Mango','Watermelon']
s.index = ind
s

Appel         10
Banana        20
orange        30
Mango         40
Watermelon    50
Name: calouries, dtype: int64

In [11]:
s['Appel']

np.int64(10)

In [12]:
#It's not work by passing updated indexing using "iloc"...Here we still wants to pass actual indexing valued ex: 0,1,2,3...
 s.iloc['Appel'] #Ivalid
s.iloc[0] #valid

IndentationError: unexpected indent (ipython-input-2228339588.py, line 2)

In [13]:
# loc --> Label Based Indexing
# It over-come the problem in 'iloc'
# In label based indexing your stop and start values are included in the Output.

s.loc['Appel']

np.int64(10)

In [14]:
s.loc['Appel':'orange']

Appel     10
Banana    20
orange    30
Name: calouries, dtype: int64

In [15]:
# creating Series using Dictionary
fruit_calories = {
    "Apple": 52,
    "Banana": 89,
    "Orange": 47,
    "Strawberry": 32,
    "Grapes": 69,
    "Watermelon": 30,
    "Mango": 60,
    "Pineapple": 50,
    "Avocado": 160, # Higher in healthy fats
    "Kiwi": 61
}
s2 = pd.Series(fruit_calories,name = "calories")
s2

Apple          52
Banana         89
Orange         47
Strawberry     32
Grapes         69
Watermelon     30
Mango          60
Pineapple      50
Avocado       160
Kiwi           61
Name: calories, dtype: int64

In [16]:
#Conditionl Selection:
s2[s2>40]

Apple         52
Banana        89
Orange        47
Grapes        69
Mango         60
Pineapple     50
Avocado      160
Kiwi          61
Name: calories, dtype: int64

In [17]:
# Logical operators: and,or,not
# and ---> &
s2[(s2>40) & (s2<70)]

Apple        52
Orange       47
Grapes       69
Mango        60
Pineapple    50
Kiwi         61
Name: calories, dtype: int64

In [18]:
# or ---> |
s2[(s2>40) | (s2<70)]

Apple          52
Banana         89
Orange         47
Strawberry     32
Grapes         69
Watermelon     30
Mango          60
Pineapple      50
Avocado       160
Kiwi           61
Name: calories, dtype: int64

In [19]:
# not ---> ~
s2[~(s2 > 40)]

Strawberry    32
Watermelon    30
Name: calories, dtype: int64

In [20]:
# modification in Series
s2['Apple'] = 100
s2

Apple         100
Banana         89
Orange         47
Strawberry     32
Grapes         69
Watermelon     30
Mango          60
Pineapple      50
Avocado       160
Kiwi           61
Name: calories, dtype: int64